import { shoppinglist } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const { ctx } = api.useContext();
  const { mutate, isLoading: isPosting } = api.item.addItem.useMutation({
    onSuccess: (item) => {
      setItems((prev) => [...prev, item]);
      // setInput("");
      // void ctx.item.getAll.invalidate();
    },
    onError: () => {
      console.log("Error");
      // toast.error("Failed to post!");
    },
  });

  const [items, setItems] = useState<shoppinglist[]>([]);

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="rounded-md bg-violet-500 p-2 text-sm text-white transition hover:bg-violet-700"
          >
            Add Item
          </button>
        </div>
        <ul className="mt-4">
          {items.map((item) => (
            <li key={item.id} className="flex items-center justify-between">
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
