import { shoppinglist } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ItemModal from "../components/ItemModal";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [status, setStatus] = useState<boolean>(false);
  const [items, setItems] = useState<shoppinglist[]>([]);
  const { data: itemsData, isLoading } = api.item.getItems.useQuery(undefined, {
    onSuccess: (items) => {
      setItems(items);
    },
  });

  if (!itemsData || isLoading) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status && <ItemModal setStatus={setStatus} setItems={setItems} />}
      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="rounded-md bg-violet-500 p-2 text-sm text-white transition hover:bg-violet-700"
            onClick={() => setStatus(true)}
          >
            Add Item
          </button>
        </div>
        <ul className="mt-4">
          {items.map((item) => (
            <li key={item.id} className="flex items-center justify-between">
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
