import { shoppinglist } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ItemModal from "../components/ItemModal";
import { api } from "~/utils/api";
import { HiX } from "react-icons/hi";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  const [status, setStatus] = useState<boolean>(false);
  const [items, setItems] = useState<shoppinglist[]>([]);
  const [checkedItems, setCheckedItems] = useState<shoppinglist[]>([]);
  const { data: itemsData, isLoading } = api.item.getItems.useQuery(undefined, {
    onSuccess: (shoppingItems) => {
      setItems(shoppingItems);
      const checked = shoppingItems.filter((item) => item.checked)
      setCheckedItems(checked)
    },
  });
  const { mutate: deleteItem } = api.item.deleteItem.useMutation({
    onSuccess(shoppingItem) {
      setItems((prev) => prev.filter((item) => item.id !== shoppingItem.id));
    },
  });
  const { mutate: toggleCheck } = api.item.toggleCheck.useMutation({
    onSuccess: (shoppingItem) => {
      if (checkedItems.some((item) => item.id === shoppingItem.id)) {
        setCheckedItems((prev) =>
          prev.filter((item) => item.id !== shoppingItem.id)
        );
      } else {
        setCheckedItems((prev) => [...prev, shoppingItem]);
      }
    },
  });

  if (!itemsData || isLoading) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status && <ItemModal setStatus={setStatus} setItems={setItems} />}
      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="rounded-md bg-violet-500 p-2 text-sm text-white transition hover:bg-violet-700"
            onClick={() => setStatus(true)}
          >
            Add Item
          </button>
        </div>
        <ul className="mt-4">
          {items.map((item) => {
            const { id, name } = item;
            return (
              <li key={item.id} className="flex items-center justify-between">
                <div className="relative">
                  <div className="pointer-events-none absolute inset-0 flex origin-left items-center justify-center">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{
                        width: checkedItems.some((item) => item.id === id)
                          ? "100%"
                          : 0,
                      }}
                      transition={{ duration: 0.2, ease: "easeInOut" }}
                      className="h-[2px] w-full translate-y-px bg-red-500"
                    />
                  </div>
                  <span
                    onClick={() =>
                      toggleCheck({
                        id,
                        checked: checkedItems.some((item) => item.id === id) ? false: true,
                      })
                    }
                  >
                    {name}
                  </span>
                </div>
                <HiX
                  onClick={() => deleteItem({ id })}
                  className="cursor-pointer text-lg text-red-600"
                />
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
};

export default Home;
